/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteFacturas;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARTHA
 */
public class VentanaSeccionFerreteria extends javax.swing.JFrame {

    DefaultTableModel modeloTabla = new DefaultTableModel();
    DefaultTableModel modelo;
    /**
     * Creates new form VentanaSeccionFerreteria
     */
    public VentanaSeccionFerreteria() {
        
        CargarModeloTabla();
        
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void CargarModeloTabla(){
        
        modeloTabla.addColumn("Seccion");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Marca");
        modeloTabla.addColumn("Importado");
        modeloTabla.addColumn("Precio");
        
        leerTexto();
    }
    
    private void leerTexto(){
        
        String cadena,fila[];
        
        try {
            FileReader lector = new FileReader("C:\\Users\\MARTHA\\Documents\\ArchivosFactura\\Ferreteria.txt");//la clase FileReader retorna una excepcion de tipo FileNotFoundException
            
            BufferedReader lectura = new BufferedReader(lector);//al bufferedReader se le pasa como parametro un archivo de lectura
            
            cadena = lectura.readLine();//la funcion readLine retorna una excepcion de tipo IOException
            
            while(cadena!=null){
                
                fila = cadena.split("%");//La funcion Split corta la cadena cuando encuentre el simbolo %
                
                modeloTabla.addRow(fila);//Agrega una fila de lo que haya en la variable fila
                
                cadena = lectura.readLine();
                
            }
            
        } catch (FileNotFoundException ex) {
            System.err.println("Error, "+ex);
            
        } catch (IOException ex) {
            
            System.err.println("Error, "+ex);
            
        }
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        BotonAgregarProducto = new javax.swing.JButton();
        EliminarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Productos Ferreteria");
        Panel.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        Tabla.setModel(modeloTabla);
        jScrollPane2.setViewportView(Tabla);

        Panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 110));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        BotonAgregarProducto.setText("Agregar Producto");
        BotonAgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarProductoMouseClicked(evt);
            }
        });
        Panel.add(BotonAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        EliminarProducto.setText("Eliminar Producto");
        EliminarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarProductoMouseClicked(evt);
            }
        });
        Panel.add(EliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jScrollPane1.setViewportView(Panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarProductoMouseClicked
        // TODO add your handling code here:
        
        VentanaAgregarProducto ventana = new VentanaAgregarProducto(this,true);
        
        dispose();
        
        ventana.setVisible(true);
        
        
    }//GEN-LAST:event_BotonAgregarProductoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal ventana = new VentanaPrincipal();
        
        dispose();
        
        ventana.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EliminarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarProductoMouseClicked
        // TODO add your handling code here:
        
        Eliminar();
        String fila2 = String.valueOf(Tabla.getSelectedRow());
        
        ArchivoFerreteria archivo = new ArchivoFerreteria();
        
        archivo.crearArchivoFerreteria();
        
        
        
        
    }//GEN-LAST:event_EliminarProductoMouseClicked

    private void Eliminar(){
        
        int fila;
        int respuesta;
        try{
            
            fila = Tabla.getSelectedRow();
            
            if(fila ==-1){
                JOptionPane.showMessageDialog(null,"Debe selecionar una fila");
            }else{
                respuesta = JOptionPane.showConfirmDialog(null,"¿Esta seguro de eliminar este producto?","Eliminar",JOptionPane.YES_NO_OPTION);
                if(respuesta == JOptionPane.YES_OPTION){
                    modelo = (DefaultTableModel)Tabla.getModel();
                    modelo.removeRow(fila);
                }
            }
            
        }catch(Exception e){
            System.err.println("error, "+e);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSeccionFerreteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSeccionFerreteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSeccionFerreteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSeccionFerreteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSeccionFerreteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarProducto;
    private javax.swing.JButton EliminarProducto;
    private javax.swing.JPanel Panel;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
